### ISSUE TITLE
Nabu geoconnex e2e action appears to be using wrong branch

### ISSUE THREAD

**Issue by C-Loftus** [internetofwater/nabu#151]
Had a bug and couldn't understand why my fixed wasn't solving it

It appears that our github actions pipeline is somewhere using the wrong branch.

https://github.com/internetofwater/nabu/blob/master/.github/workflows/geoconnex_e2e.yml#L21

scheduler's action.yml uses its master branch by default but on a pr it seems to still be using the master branch for some reason
https://github.com/internetofwater/scheduler/blob/main/action.yml#L18

**Comment by C-Loftus** [comment]
Believe this is fixed with https://github.com/internetofwater/scheduler/pull/151

Tested with the linter action and I believe all our actions in nabu are right

```yml
# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: Go Lint

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: v1.24
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
```
